# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/alex/GitHub/IFFT_Verilog/Verilog/OFDM/ofdm_baseband/ofdm_baseband.tmp/Pilot_Insertion_v0_1_project/Pilot_Insertion_v0_1_project.cache/wt [current_project]
set_property parent.project_path /home/alex/GitHub/IFFT_Verilog/Verilog/OFDM/ofdm_baseband/ofdm_baseband.tmp/Pilot_Insertion_v0_1_project/Pilot_Insertion_v0_1_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/alex/vivado/ip_repo/frame_counter_1.0
  /home/alex/vivado/ip_repo
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_cores
  /home/alex/Documents/Vivado/ip_repo/GitHub/ip_repo/OFDM_Controller_0.2
} [current_project]
set_property ip_output_repo /home/alex/GitHub/IFFT_Verilog/Verilog/OFDM/ofdm_baseband/ofdm_baseband.tmp/Pilot_Insertion_v0_1_project/Pilot_Insertion_v0_1_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/frame_counter.v
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/Pilot_Top.v
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/Pilot_Insertion_v0_1_S00_AXI.v
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/Pilot_Insertion_v0_1_S00_AXIS.v
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/Pilot_Insertion_v0_1_M00_AXIS.v
  /home/alex/vivado/ip_repo/Pilot_Insertion_0.1/hdl/Pilot_Insertion_v0_1.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Pilot_Insertion_v0_1 -part xc7z020clg484-1


write_checkpoint -force -noxdef Pilot_Insertion_v0_1.dcp

catch { report_utilization -file Pilot_Insertion_v0_1_utilization_synth.rpt -pb Pilot_Insertion_v0_1_utilization_synth.pb }
